### PR TITLE
Form validation

### LINKED ISSUE #137: Email addresses using angle brackets cause XML generation to fail
The contact fields allow the email addresses to be formatted using display names i.e. **firstname lastname &lt;email@address.tld&gt;**, while this format is valid as far as the RFC is concerned the presence of the brackets causes issues when generating the XML.

For the sake of simplicity, a validation should be run on the email address field to notify the user to use the basic email address format without display name or it should just be automatically scrubbed when saving into firebase.

### PR DESCRIPTION
**Pull request by n-a-t-e**
This PR adds form validation to a few fields 
 - URLs (in contacts and resources)
 - Email
 - DOI

Fixes #137

### CODE REVIEW

**Review by sjbruce — APPROVED** [review]
Validation appears to be working well, basic email addresses only will be recognized, URLs and DOIs are also good.

File: src/utils/validate.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import validator from "validator";
 
 export const validateEmail = (email) => !email || validator.isEmail(email);
-export const validateURL = (url) => !url || validator.isEmail(url);
+export const validateURL = (url) => !url || validator.isURL(url);
```
Comment (n-a-t-e) [inline src/utils/validate.js:4]: Nice catch
